package cn.hylstudio.skykoma.data.collector.entity.neo4j.projection;

import cn.hylstudio.skykoma.data.collector.entity.neo4j.ProjectEntity;
import lombok.Data;

@Data
public class ProjectEntityNodeProjection {

    private String id;
    private String key;
    private String name;
    private Long createdAt;
    private Long updatedAt;

    public ProjectEntityNodeProjection() {
    }

    public ProjectEntityNodeProjection(String key) {
        this.key = key;
    }

    public ProjectEntityNodeProjection(ProjectEntity entity) {
        // -------------- generated by skykoma begin --------------
        this.id = entity.getId();
        this.key = entity.getKey();
        this.name = entity.getName();
        this.createdAt = entity.getCreatedAt();
        this.updatedAt = entity.getUpdatedAt();
        // -------------- generated by skykoma end --------------

    }
}
