package cn.hylstudio.skykoma.data.collector.entity.neo4j;

import cn.hylstudio.skykoma.data.collector.model.ModuleDto;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.neo4j.core.schema.*;
import org.springframework.data.neo4j.core.support.UUIDStringGenerator;

import java.util.List;

@Node
@Data
public class ModuleEntity {
    @Id
    @GeneratedValue(generatorClass = UUIDStringGenerator.class)
    private String id;
    @Property
    private String name;
    @Relationship(type = "MODULE_ROOT", direction = Relationship.Direction.OUTGOING)
    private List<ModuleRootRel> roots;
    @Relationship(type = "DEPENDS", direction = Relationship.Direction.OUTGOING)
    private List<DependencyEntity> dependencies;
    @CreatedDate
    @Property
    private Long createdAt;

    @LastModifiedDate
    @Property
    private Long updatedAt;

    public ModuleEntity() {
    }

    public ModuleEntity(ModuleDto moduleDto) {
        // -------------- generated by skykoma begin --------------
        this.name = moduleDto.getName();
        // -------------- generated by skykoma end --------------

    }
}
