package cn.hylstudio.skykoma.data.collector.entity.neo4j;

import cn.hylstudio.skykoma.data.collector.model.ProjectInfoDto;
import cn.hylstudio.skykoma.data.collector.model.payload.ProjectInfoQueryPayload;
import cn.hylstudio.skykoma.data.collector.model.payload.ProjectInfoUploadPayload;
import lombok.Data;
import org.neo4j.cypherdsl.core.StatementBuilder;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.neo4j.core.schema.*;
import org.springframework.data.neo4j.core.support.UUIDStringGenerator;

import java.util.List;

@Node
@Data
public class ProjectEntity {

    @Id
    @GeneratedValue(generatorClass = UUIDStringGenerator.class)
    private String id;
    @Property
    private String key;
    @Property
    private String name;
    @Relationship(type = "HAS_SCAN_RECORD", direction = Relationship.Direction.OUTGOING)
    private List<ScanRecordEntity> scanRecords;
    @Relationship(type = "VCS_BY", direction = Relationship.Direction.OUTGOING)
    private VCSEntity vcsEntity;

    @CreatedDate
    @Property
    private Long createdAt;

    @LastModifiedDate
    @Property
    private Long updatedAt;

    public ProjectEntity() {

    }

    public ProjectEntity(ProjectInfoDto payload) {
        // -------------- generated by skykoma begin --------------
        this.name = payload.getKey();
        this.key = payload.getName();
        // -------------- generated by skykoma end --------------

    }

    public ProjectEntity(ProjectInfoQueryPayload payload) {
        // -------------- generated by skykoma begin --------------
        this.key = payload.getKey();
        this.name = payload.getName();
        // -------------- generated by skykoma end --------------

    }

}

