package cn.hylstudio.skykoma.data.collector.model;

import cn.hylstudio.skykoma.data.collector.entity.neo4j.FileEntity;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.File;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

@Data
public class FileDto {
    public static final String TYPE_FOLDER = "folder";
    public static final String TYPE_FILE = "file";
    private String name;
    private String type;//file folder
    private String relativePath;
    private String absolutePath;
    private List<FileDto> subFiles;
    private String psiFileJson;

    public FileDto() {
    }

    public FileDto(FileEntity v) {
        // -------------- generated by skykoma begin --------------
        this.name = v.getName();
        this.type = v.getType();
        this.relativePath = v.getRelativePath();
        this.absolutePath = v.getAbsolutePath();
        this.subFiles = v.getSubFiles().stream().map(FileDto::new).collect(Collectors.toList());
        // -------------- generated by skykoma end --------------

    }
}
