package cn.hylstudio.skykoma.data.collector.model;

import cn.hylstudio.skykoma.data.collector.entity.neo4j.ModuleEntity;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
public class ModuleDto {
    private String name;
    private List<FileDto> srcRoots;
    private List<FileDto> testSrcRoots;
    private List<FileDto> resRoots;
    private List<FileDto> testResRoots;

    public ModuleDto() {
    }

    public ModuleDto(ModuleEntity moduleEntity) {
        // -------------- generated by skykoma begin --------------
        this.name = moduleEntity.getName();

        // -------------- generated by skykoma end --------------

    }
}
