package cn.hylstudio.skykoma.data.collector.model;

import cn.hylstudio.skykoma.data.collector.entity.neo4j.VCSEntity;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
public class VCSEntityDto {
    private String id;
    private String vcsType;
    private String name;
    private String path;

    public VCSEntityDto() {
    }

    public VCSEntityDto(VCSEntity vcsEntity) {
        // -------------- generated by skykoma begin --------------
        this.id = vcsEntity.getId();
        this.vcsType = vcsEntity.getVcsType();
        this.name = vcsEntity.getName();
        this.path = vcsEntity.getPath();
        // -------------- generated by skykoma end --------------

    }
}
